#!/usr/bin/env bash
PPATH=$(realpath ..)
USE_SCORING=0
. ../../../testdata_tools/gen.sh

use_solution david.cpp opt

compile random_generator.py

sample 1
sample 2
sample 3

tc triangle random_generator 3 3 100 circle
tc close-line random_generator 0 0 0 close_line
tc batman random_generator 0 0 0 batman

tc tiny-circle random_generator 8 10 100000 circle
tc tiny-star random_generator 8 10 100000 star
tc tiny-comb random_generator 8 10 100000 comb

tc polygon-20 random_generator 20 20 20000 randomsimple
tc polygon-100 random_generator 100 100 10000 randomsimple

tc small-circle random_generator 80 100 1000000000 circle
tc small-star random_generator 80 100 1000000000 star
tc small-comb random_generator 80 100 1000000000 comb

tc polygon-250 random_generator 250 250 25000 randomsimple
tc polygon-800 random_generator 800 800 800000 randomsimple
tc polygon-2000 random_generator 2000 2000 200000 randomsimple

tc medium-circle random_generator 2400 3000 1000000000 circle
tc medium-star random_generator 2400 3000 1000000000 star
tc medium-comb random_generator 2400 3000 1000000000 comb
tc medium-spiral random_generator 2400 3000 1000000000 spiral

tc large-circle random_generator 40000 50000 1000000000 circle
tc large-star random_generator 40000 50000 1000000000 star
tc large-comb random_generator 40000 50000 1000000000 comb
tc large-spiral random_generator 40000 50000 1000000000 spiral

tc large-star-tight random_generator 40000 50000 1000000 star
tc large-comb-tight random_generator 40000 50000 1000000 comb

/usr/bin/python3 -m pip install Pillow
for file in $(find . -name *.in | sort); do
    imgpath="${file%.in}.png"
    ansfile="${file%.in}.ans"
    if [[ -L "$file" ]]; then
        resolvedfile=$(realpath --relative-to $(dirname $file) $(readlink -f "$file"))
        resolvedpath="${resolvedfile%.in}.png"
        #echo "Linking $imgpath to $resolvedpath"
        ln -s "$resolvedpath" "$imgpath"
        resolvedpath="${resolvedfile%.in}.ans"
    else
        echo "Generating $imgpath"
        ./visualizer.py "$imgpath" "$ansfile" < "$file"
    fi
done;
